image:
  file: .gitpod.Dockerfile

tasks:
  - init: |
      npm install
      which serverless || npm install -g serverless
      which localstack || pip install localstack
  - name: Run LocalStack
    command: |
      localstack start
    openMode: split-right
  - name: Deploy the app
    command: |
      echo "Deploying Serverless app to local environment"
      SLS_DEBUG=1 serverless deploy --stage local
  - name: Send a test request
    command: |
      apiId=$(awslocal apigateway get-rest-apis --output json | jq -r '.items[] | select(.name=="local-localstack-demo") | .id')
      requestID=$(curl -s -d '{}' http://$apiId.execute-api.localhost.localstack.cloud:4566/local/requests | jq -r .requestID)
      echo "Received request ID '$requestID'"
      for i in {1..10}; do echo "Polling for processing result to appear in s3://archive-bucket/..."; awslocal s3 ls s3://archive-bucket/ | grep $requestID && exit; sleep 3; done
  - name: Run code linter
    command: |
      npm run lint
      flake8 demo

ports:
  - port: 4566
    onOpen: open-preview

# vscode:
#   extensions:
#     - ms-python.python
#     - eamodio.gitlens
#     - redhat.vscode-yaml

# # Variables for AWS and LocalStack
# env:
#   - AWS_ACCESS_KEY_ID=test
#   - AWS_SECRET_ACCESS_KEY=test
#   - AWS_DEFAULT_REGION=us-east-1
